### ISSUE TITLE
npm run start Syntax Error.

### ISSUE THREAD

**Issue by s9013xx** [onitsoft/nexchange-open-client-react#349]
Hi, I follow README file install npm and node, and then git code, finall run "npm run start", but I get some error below : 

Is npm or node version not match?

joe@ubuntu:~/nexchange-open-client-react$ npm run start

> nexchange-open-client-react@0.1.0 start /home/joe/nexchange-open-client-react
> node scripts/start.js

/home/joe/nexchange-open-client-react/scripts/start.js:23
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! nexchange-open-client-react@0.1.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nexchange-open-client-react@0.1.0 start script 'node scripts/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nexchange-open-client-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nexchange-open-client-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nexchange-open-client-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/joe/nexchange-open-client-react/npm-debug.log

Thanks you!

**Comment by s9013xx** [comment]
below is /home/joe/nexchange-open-client-react/npm-debug.log     Thanks you!

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle nexchange-open-client-react@0.1.0~prestart: nexchange-open-client-react@0.1.0
6 silly lifecycle nexchange-open-client-react@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle nexchange-open-client-react@0.1.0~start: nexchange-open-client-react@0.1.0
8 verbose lifecycle nexchange-open-client-react@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle nexchange-open-client-react@0.1.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/joe/nexchange-open-client-react/node_modules/.bin:/usr/lib/jdk/jdk1.7.0_45/bin:/usr/lib/jdk/jdk1.7.0_45/jre/bin:/home/joe/.sdkman/candidates/grails/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle nexchange-open-client-react@0.1.0~start: CWD: /home/joe/nexchange-open-client-react
11 silly lifecycle nexchange-open-client-react@0.1.0~start: Args: [ '-c', 'node scripts/start.js' ]
12 silly lifecycle nexchange-open-client-react@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle nexchange-open-client-react@0.1.0~start: Failed to exec start script
14 verbose stack Error: nexchange-open-client-react@0.1.0 start: `node scripts/start.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid nexchange-open-client-react@0.1.0
16 verbose cwd /home/joe/nexchange-open-client-react
17 error Linux 4.4.0-21-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error nexchange-open-client-react@0.1.0 start: `node scripts/start.js`
22 error Exit status 1
23 error Failed at the nexchange-open-client-react@0.1.0 start script 'node scripts/start.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the nexchange-open-client-react package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node scripts/start.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs nexchange-open-client-react
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls nexchange-open-client-react
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
~

**Comment by s9013xx** [comment]
It can work when I use the last version of npm and node.

Thanks!
